# Generated by Django 4.2.1 on 2023-11-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_bill_total_alter_bill_detail_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_detail',
            name='id_bill',
        ),
        migrations.RemoveField(
            model_name='bill_detail',
            name='id_branch',
        ),
        migrations.RemoveField(
            model_name='bill_detail',
            name='id_car',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='id_customer',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='id_employee',
        ),
        migrations.RemoveField(
            model_name='quotation_detail',
            name='id_car',
        ),
        migrations.RemoveField(
            model_name='quotation_detail',
            name='id_quotation',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Bill_detail',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='Quotation_detail',
        ),
    ]
